/**
 * Real local-auth browser flow for the disposable PostgreSQL lane.
 *
 * This helper deliberately observes the requests made by the page instead of
 * creating a second API client. The only credentials it reads are generated by
 * `run-local-auth-live-stack.mjs` for this process; token bytes stay in memory
 * long enough to prove the server-issued replacement is used by the SPA.
 */
import { expect, type Page, type Request, type Response } from '@playwright/test';

import type { components } from '../../../src/api/generated/platform-api.types';

const LIVE_EMAIL_ENV = 'FCC_LOCAL_AUTH_LIVE_EMAIL';
const LIVE_INITIAL_PASSWORD_ENV = 'FCC_LOCAL_AUTH_LIVE_INITIAL_PASSWORD';
const LIVE_NEW_PASSWORD_ENV = 'FCC_LOCAL_AUTH_LIVE_NEW_PASSWORD';

const LOGIN_PATH = '/platform/auth/login';
const CHANGE_PASSWORD_PATH = '/platform/auth/change-password';
const PROTECTED_PATH = '/platform/chambers';

type JsonObject = Readonly<Record<string, unknown>>;

type LocalAuthTokenEnvelope = components['schemas']['LocalAuthTokenEnvelope'];
type LocalLoginRequest = components['schemas']['LocalLoginRequest'];
type LocalChangePasswordRequest = components['schemas']['LocalChangePasswordRequest'];
type LocalLogoutRequest = components['schemas']['LocalLogoutRequest'];

export interface LocalAuthLiveCredentials {
  readonly email: string;
  readonly initialPassword: string;
  readonly newPassword: string;
}

export interface LocalAuthLiveLedger {
  readonly loginRequestPath: typeof LOGIN_PATH;
  readonly loginResponseStatus: number;
  readonly changePasswordRequestPath: typeof CHANGE_PASSWORD_PATH;
  readonly changePasswordResponseStatus: number;
  readonly protectedRequestPath: typeof PROTECTED_PATH;
  readonly protectedResponseStatus: number;
  readonly protectedResponseWasJson: boolean;
  readonly oldTokenResponseStatus: number;
  readonly logoutResponseStatus: number;
}

export interface LocalAuthLiveResult {
  /** Kept in memory for the caller's replacement-token assertion only. */
  readonly loginAccessToken: string;
  /** Kept in memory for the caller's protected-request assertion only. */
  readonly replacementAccessToken: string;
  readonly ledger: LocalAuthLiveLedger;
}

function requiredCredential(
  env: Readonly<Record<string, string | undefined>>,
  name: string,
): string {
  const value = env[name];
  if (typeof value !== 'string' || value.length === 0) {
    throw new Error(`local-auth live lane is missing generated credential ${name}`);
  }
  return value;
}

export function readLocalAuthLiveCredentials(
  env: Readonly<Record<string, string | undefined>> = process.env,
): LocalAuthLiveCredentials {
  const credentials = {
    email: requiredCredential(env, LIVE_EMAIL_ENV),
    initialPassword: requiredCredential(env, LIVE_INITIAL_PASSWORD_ENV),
    newPassword: requiredCredential(env, LIVE_NEW_PASSWORD_ENV),
  };
  if (credentials.initialPassword === credentials.newPassword) {
    throw new Error('local-auth live lane requires distinct generated initial and new passwords');
  }
  return credentials;
}

function isObject(value: unknown): value is JsonObject {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function assertRequestBody(request: Request, expected: JsonObject, label: string): void {
  let body: unknown;
  try {
    body = request.postDataJSON();
  } catch {
    throw new Error(`${label} request did not carry a JSON body`);
  }
  if (!isObject(body)) throw new Error(`${label} request body was not an object`);
  for (const [key, value] of Object.entries(expected)) {
    if (body[key] !== value)
      throw new Error(`${label} request body did not use the generated form value`);
  }
}

function apiRequestFor(origin: string, method: string, pathname: string) {
  return (request: Request): boolean => {
    const url = new URL(request.url());
    return url.origin === origin && url.pathname === pathname && request.method() === method;
  };
}

function apiResponseFor(origin: string, method: string, pathname: string) {
  return (response: Response): boolean =>
    apiRequestFor(origin, method, pathname)(response.request());
}

function tokenEnvelope(
  payload: unknown,
  expectedForcePasswordChange: boolean | undefined,
  label: string,
): Pick<LocalAuthTokenEnvelope, 'access_token' | 'refresh_token'> {
  if (!isObject(payload)) throw new Error(`${label} response was not a JSON object`);
  const accessToken = payload.access_token;
  const refreshToken = payload.refresh_token;
  const expiresIn = payload.expires_in;
  const tokenType = payload.token_type;
  if (
    typeof accessToken !== 'string' ||
    accessToken.length === 0 ||
    typeof refreshToken !== 'string' ||
    refreshToken.length === 0 ||
    typeof expiresIn !== 'number' ||
    !Number.isFinite(expiresIn) ||
    expiresIn <= 0 ||
    typeof tokenType !== 'string' ||
    tokenType.toLowerCase() !== 'bearer'
  ) {
    throw new Error(`${label} response did not carry the current token envelope`);
  }
  if (
    expectedForcePasswordChange !== undefined &&
    payload.force_password_change !== expectedForcePasswordChange
  ) {
    throw new Error(`${label} response carried an unexpected password-change state`);
  }
  return { access_token: accessToken, refresh_token: refreshToken };
}

async function requireJsonResponse(response: Response, label: string): Promise<JsonObject> {
  const contentType = response.headers()['content-type'] ?? '';
  if (!contentType.toLowerCase().includes('json')) {
    throw new Error(`${label} response was not JSON`);
  }
  let payload: unknown;
  try {
    payload = await response.json();
  } catch {
    throw new Error(`${label} response body was not valid JSON`);
  }
  if (!isObject(payload)) throw new Error(`${label} response body was not an object`);
  return payload;
}

/**
 * Navigate and complete first login through the real local-auth forms.
 *
 * The assertions intentionally use browser request/response events. There is
 * no direct request context, route interception, storage writer, or internal
 * API origin in this path.
 */
export async function loginWithRealLocalAuth(page: Page): Promise<LocalAuthLiveResult> {
  const credentials = readLocalAuthLiveCredentials();
  await page.goto('/');
  const origin = new URL(page.url()).origin;

  await page.waitForURL((url) => url.origin === origin && url.pathname === '/login');
  await expect(page.locator('.login-route')).toBeVisible();

  const loginRequestPromise = page.waitForRequest(apiRequestFor(origin, 'POST', LOGIN_PATH));
  const loginResponsePromise = page.waitForResponse(apiResponseFor(origin, 'POST', LOGIN_PATH));
  await page.locator('#login-email').fill(credentials.email);
  await page.locator('#login-password').fill(credentials.initialPassword);
  await page.locator('.login-route form button[type="submit"]').click();

  const [loginRequest, loginResponse] = await Promise.all([
    loginRequestPromise,
    loginResponsePromise,
  ]);
  assertRequestBody(
    loginRequest,
    {
      email: credentials.email,
      password: credentials.initialPassword,
    } satisfies LocalLoginRequest,
    'login',
  );
  if (loginResponse.status() !== 200) throw new Error('local login did not return HTTP 200');
  const loginPayload = await requireJsonResponse(loginResponse, 'local login');
  const loginTokens = tokenEnvelope(loginPayload, true, 'local login');

  await page.waitForURL((url) => url.origin === origin && url.pathname === '/change-password');
  await expect(page.locator('.change-password-route')).toBeVisible();
  if ((await page.locator('.app-shell').count()) !== 0) {
    throw new Error('the dashboard shell rendered before the forced password change');
  }

  const invalidCurrentRequestPromise = page.waitForRequest(
    apiRequestFor(origin, 'POST', CHANGE_PASSWORD_PATH),
  );
  const invalidCurrentResponsePromise = page.waitForResponse(
    apiResponseFor(origin, 'POST', CHANGE_PASSWORD_PATH),
  );
  await page.locator('#current-password').fill(`${credentials.initialPassword}-wrong`);
  await page.locator('#new-password').fill(credentials.newPassword);
  await page.locator('.change-password-route form button[type="submit"]').click();
  const [invalidCurrentRequest, invalidCurrentResponse] = await Promise.all([
    invalidCurrentRequestPromise,
    invalidCurrentResponsePromise,
  ]);
  assertRequestBody(
    invalidCurrentRequest,
    {
      current_password: `${credentials.initialPassword}-wrong`,
      new_password: credentials.newPassword,
    } satisfies LocalChangePasswordRequest,
    'invalid current password',
  );
  if (invalidCurrentResponse.status() !== 401) {
    throw new Error('wrong current password did not return HTTP 401');
  }
  await expect(page.locator('.change-password-route__error')).toBeVisible();

  const policyRequestPromise = page.waitForRequest(
    apiRequestFor(origin, 'POST', CHANGE_PASSWORD_PATH),
  );
  const policyResponsePromise = page.waitForResponse(
    apiResponseFor(origin, 'POST', CHANGE_PASSWORD_PATH),
  );
  await page.locator('#current-password').fill(credentials.initialPassword);
  await page.locator('#new-password').fill('weak');
  await page.locator('.change-password-route form button[type="submit"]').click();
  const [policyRequest, policyResponse] = await Promise.all([
    policyRequestPromise,
    policyResponsePromise,
  ]);
  assertRequestBody(
    policyRequest,
    {
      current_password: credentials.initialPassword,
      new_password: 'weak',
    } satisfies LocalChangePasswordRequest,
    'password policy',
  );
  if (policyResponse.status() !== 400) {
    throw new Error('policy-violating password did not return HTTP 400');
  }
  await expect(page.locator('.change-password-route__error')).toBeVisible();

  const changeRequestPromise = page.waitForRequest(
    apiRequestFor(origin, 'POST', CHANGE_PASSWORD_PATH),
  );
  const changeResponsePromise = page.waitForResponse(
    apiResponseFor(origin, 'POST', CHANGE_PASSWORD_PATH),
  );
  const protectedRequestPromise = page.waitForRequest(apiRequestFor(origin, 'GET', PROTECTED_PATH));
  const protectedResponsePromise = page.waitForResponse(
    apiResponseFor(origin, 'GET', PROTECTED_PATH),
  );
  await page.locator('#current-password').fill(credentials.initialPassword);
  await page.locator('#new-password').fill(credentials.newPassword);
  await page.locator('.change-password-route form button[type="submit"]').click();

  const [changeRequest, changeResponse] = await Promise.all([
    changeRequestPromise,
    changeResponsePromise,
  ]);
  assertRequestBody(
    changeRequest,
    {
      current_password: credentials.initialPassword,
      new_password: credentials.newPassword,
    } satisfies LocalChangePasswordRequest,
    'password change',
  );
  if (changeResponse.status() !== 200) {
    throw new Error('local password change did not return HTTP 200');
  }
  const changePayload = await requireJsonResponse(changeResponse, 'local password change');
  const replacementTokens = tokenEnvelope(changePayload, false, 'local password change');
  if (replacementTokens.access_token === loginTokens.access_token) {
    throw new Error('password change did not return a replacement access token');
  }

  const [protectedRequest, protectedResponse] = await Promise.all([
    protectedRequestPromise,
    protectedResponsePromise,
  ]);
  const authorization = protectedRequest.headers().authorization;
  if (authorization !== `Bearer ${replacementTokens.access_token}`) {
    throw new Error('the protected browser request did not use the replacement access token');
  }
  if (protectedResponse.status() < 200 || protectedResponse.status() >= 300) {
    throw new Error('the protected browser request did not return a 2xx response');
  }
  await requireJsonResponse(protectedResponse, 'protected dashboard request');

  await page.waitForURL((url) => url.origin === origin && url.pathname === '/');
  await expect(page.locator('.app-shell')).toBeVisible();
  await expect(page.getByTestId('home-workbench')).toBeVisible();

  const oldTokenResponseStatus = await page.evaluate(
    async ({ pathname, token }) => {
      const response = await fetch(pathname, {
        headers: { Accept: 'application/json', Authorization: `Bearer ${token}` },
      });
      return response.status;
    },
    { pathname: PROTECTED_PATH, token: loginTokens.access_token },
  );
  if (oldTokenResponseStatus < 400 || oldTokenResponseStatus >= 500) {
    throw new Error('the pre-change access token was not rejected after password change');
  }

  const logoutRequestPromise = page.waitForRequest(
    apiRequestFor(origin, 'POST', '/platform/auth/logout'),
  );
  const logoutResponsePromise = page.waitForResponse(
    apiResponseFor(origin, 'POST', '/platform/auth/logout'),
  );
  await page.locator('.auth-signout-button').click();
  const [logoutRequest, logoutResponse] = await Promise.all([
    logoutRequestPromise,
    logoutResponsePromise,
  ]);
  if (logoutResponse.status() !== 200) throw new Error('local logout did not return HTTP 200');
  assertRequestBody(
    logoutRequest,
    { refresh_token: replacementTokens.refresh_token } satisfies LocalLogoutRequest,
    'local logout',
  );
  await page.waitForURL((url) => url.origin === origin && url.pathname === '/login');
  await expect(page.locator('.login-route')).toBeVisible();
  let protectedRequestsAfterLogout = 0;
  const countProtectedRequest = (request: Request): void => {
    if (apiRequestFor(origin, 'GET', PROTECTED_PATH)(request)) protectedRequestsAfterLogout += 1;
  };
  page.on('request', countProtectedRequest);
  await page.goto('/');
  await page.waitForURL((url) => url.origin === origin && url.pathname === '/login');
  page.off('request', countProtectedRequest);
  if (protectedRequestsAfterLogout !== 0) {
    throw new Error('signed-out navigation issued an authenticated protected request');
  }
  await page.reload();
  await page.waitForURL((url) => url.origin === origin && url.pathname === '/login');
  if ((await page.locator('.app-shell').count()) !== 0) {
    throw new Error('dashboard shell remained after local sign-out');
  }

  return {
    loginAccessToken: loginTokens.access_token,
    replacementAccessToken: replacementTokens.access_token,
    ledger: {
      loginRequestPath: LOGIN_PATH,
      loginResponseStatus: loginResponse.status(),
      changePasswordRequestPath: CHANGE_PASSWORD_PATH,
      changePasswordResponseStatus: changeResponse.status(),
      protectedRequestPath: PROTECTED_PATH,
      protectedResponseStatus: protectedResponse.status(),
      protectedResponseWasJson: true,
      oldTokenResponseStatus,
      logoutResponseStatus: logoutResponse.status(),
    },
  };
}
